apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: slo-rollout
  labels:
    app: demo-app
    ssentinel.io/generated-by: config-compiler
    ssentinel.io/env: dev
  annotations:
    ssentinel.io/generated-by: config-compiler
    ssentinel.io/env: dev
    ssentinel.io/renderer-ref: argo-rollouts-canary-v1
    ssentinel.io/output-kind: Rollout
    ssentinel.io/compiler-profile: demo-app-compiler-profile
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: runtime-pause-test-20260527-170724
    spec:
      containers:
      - name: demo-app
        image: registry.local:5000/sre/demo-app:runtime-pause-test-20260527-170724
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VERSION
          value: runtime-pause-test
        - name: RELEASE_TAG
          value: runtime-pause-test-20260527-170724
        - name: FAULT_RATE
          value: '0.8'
        - name: LATENCY_MS
          value: '800'
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: demo-app-error-rate
      - setWeight: 50
      - pause:
          duration: 60s
      - analysis:
          templates:
          - templateName: demo-app-error-rate
      - setWeight: 100
